services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    # environment:
    #   - MONGODB_URI=${MONGODB_URI}
    env_file:
      - ./apps/reservations/.env
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    # environment:
    #   - MONGODB_URI=${MONGODB_URI}
    #   - JWT_SECRET=${JWT_SECRET}
    #   - JWT_EXPIRATION=${JWT_EXPIRATION}
    env_file:
      - ./apps/auth/.env
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    ports:
      - '3003:3003'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    env_file:
      - ./apps/payments/.env
  mongo:
    image: mongo
    # volumes:
    # - ~/data/db:/data/db
